#pragma once

#define START_UNIT_TEST 1

#define START_EXAMPLE 1

#define EXAMPLE_01_TRIANGLE 0
#define EXAMPLE_02_QUADTTEXTURE 0
#define EXAMPLE_03_OBJMODEL 0

#define EXAMPLE_X_TEMP 0
#define EXAMPLE_X_DEBUG 1
#define EXAMPLE_X_TESTFPS 0